/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// OriginDto Indicates where a service specification was originally created.
type OriginDto string

// List of OriginDto
const (
	ORIGINDTO_SELF     OriginDto = "Self"
	ORIGINDTO_GAEB90   OriginDto = "Gaeb90"
	ORIGINDTO_GAEB2000 OriginDto = "Gaeb2000"
	ORIGINDTO_GAEB_XML OriginDto = "GaebXml"
	ORIGINDTO_OENORM   OriginDto = "Oenorm"
	ORIGINDTO_REB      OriginDto = "Reb"
	ORIGINDTO_SIA      OriginDto = "Sia"
)
