/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// ExecutionDescriptionDto struct for ExecutionDescriptionDto
type ExecutionDescriptionDto struct {
	// Elements GUID identifier.
	Id string `json:"id"`
	// This is used to store the GAEB XML Id within this IElement. This data is not used for any calculations or evaluations but only for GAEB serialization and deserialization.
	GaebXmlId                string `json:"gaebXmlId,omitempty"`
	ElementTypeDiscriminator string `json:"elementTypeDiscriminator"`
	// Blocks within an ExecutionDescription contain the actual information.
	Blocks []NoteTextDto `json:"blocks,omitempty"`
	// Labels this ExecutionDescription.
	Label string `json:"label,omitempty"`
	// Uniquely identifies this ExecutionDescription.
	Identifier  string `json:"identifier,omitempty"`
	ElementType string `json:"elementType,omitempty"`
}
