/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// DurationUnitDto This enumeration represents the unit of a duration
type DurationUnitDto string

// List of DurationUnitDto
const (
	DURATIONUNITDTO_MONTHS DurationUnitDto = "Months"
	DURATIONUNITDTO_YEARS  DurationUnitDto = "Years"
)
