/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// AdditionTypeDto Indicates the origin of an element.
type AdditionTypeDto string

// List of AdditionTypeDto
const (
	ADDITIONTYPEDTO_NONE      AdditionTypeDto = "None"
	ADDITIONTYPEDTO_BY_BUYER  AdditionTypeDto = "ByBuyer"
	ADDITIONTYPEDTO_BY_BIDDER AdditionTypeDto = "ByBidder"
)
