/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// StandardReferenceTypeDto This enumeration identifies a pre-known standard used for referencing standardized descriptions.
type StandardReferenceTypeDto string

// List of StandardReferenceTypeDto
const (
	STANDARDREFERENCETYPEDTO_UNKNOWN    StandardReferenceTypeDto = "Unknown"
	STANDARDREFERENCETYPEDTO_ST_LB      StandardReferenceTypeDto = "StLB"
	STANDARDREFERENCETYPEDTO_ST_LK      StandardReferenceTypeDto = "StLK"
	STANDARDREFERENCETYPEDTO_STLB_BAU_Z StandardReferenceTypeDto = "STLBBauZ"
)
