/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// DestinationGaebExchangePhase The GAEB exchange phase to transform to
type DestinationGaebExchangePhase string

// List of DestinationGaebExchangePhase
const (
	DESTINATIONGAEBEXCHANGEPHASE_NONE          DestinationGaebExchangePhase = "None"
	DESTINATIONGAEBEXCHANGEPHASE_BASE          DestinationGaebExchangePhase = "Base"
	DESTINATIONGAEBEXCHANGEPHASE_OFFER_REQUEST DestinationGaebExchangePhase = "OfferRequest"
	DESTINATIONGAEBEXCHANGEPHASE_OFFER         DestinationGaebExchangePhase = "Offer"
	DESTINATIONGAEBEXCHANGEPHASE_GRANT         DestinationGaebExchangePhase = "Grant"
	DESTINATIONGAEBEXCHANGEPHASE_COST_ESTIMATE DestinationGaebExchangePhase = "CostEstimate"
	DESTINATIONGAEBEXCHANGEPHASE_SIDE_OFFER    DestinationGaebExchangePhase = "SideOffer"
)
