/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// ItemNumberDto This class represents as identifier of a certain service specification's element and is uniquely within the service specification.
type ItemNumberDto struct {
	// Elements GUID identifier.
	Id string `json:"id"`
	// Will return this ItemNumber as point delimited string. Will not distinguish between upper- and lowercase and return an all-lowercase representation. Will consider first numbers, then characters, e.g. 1a is considered preceding aa.
	StringRepresentation string `json:"stringRepresentation,omitempty"`
	// Indicates if the characters and the length of the Identifiers match the current ItemNumberSchema.
	IsSchemaCompliant bool                `json:"isSchemaCompliant"`
	ItemNumberSchema  ItemNumberSchemaDto `json:"itemNumberSchema,omitempty"`
	// Collection of the single identifiers in this ItemNumber. P.e., \"02.03.004\" will have three elements \"02\", \"03\", and \"004\". Since ReadOnlyObservableCollection`1 does have the event set to protected, it can be accessed like this: (itemNumber.Identifiers as INotifyCollectionChanged).CollectionChanged
	Identifiers []string `json:"identifiers,omitempty"`
	// This indicates if this item number is at the lot level. Find out more about lots in the documentation.
	IsLot bool `json:"isLot"`
}
