/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// IElementDto Base interface definition for elements within an ElementContainerBase.
type IElementDto interface {
	isIElementDto()
}
