/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// PriceComponentDto This class provides means to store information about a price and it's composition. Note that this is referencing to a single price component, so for example a Position would have a list of PriceComponents, one for Material, one for Labour etc.
type PriceComponentDto struct {
	// The total, calculated price of this component.
	Price float32 `json:"price"`
	// The label associated with this price component. Will be taken from the parent Projects ProjectInformation.
	Label string `json:"label,omitempty"`
	// The single Calculation elements this price component is composed of.
	Values []CalculationDto `json:"values,omitempty"`
}
