/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// PositionDtoAllOf A Position is the main item type in a ServiceSpecification, holding information about tasks to be done, their prices, description, amounts etc.
type PositionDtoAllOf struct {
	// Will return the price per unit, rounded according to the project settings or the default value of three decimal places
	UnitPrice float32 `json:"unitPrice"`
	// You can use this property to directly set the unit price for this position. This will override any given PriceComponents
	UnitPriceOverride float32 `json:"unitPriceOverride,omitempty"`
	// Will return this Position's total quantity, rounded to three decimal places.
	Quantity float32 `json:"quantity"`
	// You can use this property to directly set the quantity for this position. This will override any given QuantityComponents
	QuantityOverride float32 `json:"quantityOverride,omitempty"`
	// The tag of the unit used for this positions quantity.
	UnitTag          string                  `json:"unitTag,omitempty"`
	LabourComponents LabourPriceComponentDto `json:"labourComponents,omitempty"`
	// The single price components in this Position. Price components should not be handled directly on a per-position basis but set globally in the parent Projects ProjectInformation.
	PriceComponents []PriceComponentDto `json:"priceComponents,omitempty"`
	// The quantity components of this Position.
	QuantityComponents []CalculationDto `json:"quantityComponents,omitempty"`
	// Further structuring of this Position.
	SubDescriptions []SubDescriptionDto `json:"subDescriptions,omitempty"`
	ComissionStatus ComissionStatusDto  `json:"comissionStatus"`
	// A list of positions that complement this Position. The positions are referenced by their GUIDs. It might be used together with ComplementedByQuantities in case that only a given quantity is complemented by positions.
	ComplementedBy []string `json:"complementedBy,omitempty"`
	// Will indicate if this Position is complemented in this ServiceSpecification by other Positions. It can not be set to false when there are entries in the ComplementedBy property.
	Complemented bool `json:"complemented"`
	// Indicates that the amount for this Position is to be set by the bidder.
	AmountToBeEnteredByBidder bool `json:"amountToBeEnteredByBidder"`
	// Indicates if the bidder demands for prices to be broken up into their price components.
	PriceCompositionRequired bool `json:"priceCompositionRequired"`
	// Indicates if this Position should use a different TaxRate than what is the default for the Project.
	UseDifferentTaxRate bool `json:"useDifferentTaxRate"`
	// Will return either the parent ServiceSpecification's TaxRate or it's own if it has a different value. (For example, in Germany Water has a different TaxRate than regular Positions)
	TaxRate    float32       `json:"taxRate"`
	ItemNumber ItemNumberDto `json:"itemNumber,omitempty"`
	// The rate of deductions, i.e. 0.12m means 12% price deduction.
	DeductionFactor float32 `json:"deductionFactor"`
	// Returns the product of UnitPrice times Quantity.
	TotalPrice float32 `json:"totalPrice"`
	// The total gross price for this Position.
	TotalPriceGross float32 `json:"totalPriceGross"`
	// Total gross price after applied deductions.
	TotalPriceGrossDeducted float32 `json:"totalPriceGrossDeducted"`
	// Net price after applied deductions.
	DeductedPrice float32         `json:"deductedPrice"`
	PositionType  PositionTypeDto `json:"positionType"`
	PriceType     PriceTypeDto    `json:"priceType"`
	ServiceType   ServiceTypeDto  `json:"serviceType"`
	ProductData   ProductDataDto  `json:"productData,omitempty"`
	// Short description for this DescriptionBase element.
	ShortText string `json:"shortText,omitempty"`
	// Detailed description for this DescriptionBase element. When the HtmlLongText is set, this is automatically overwritten and filled with the appropriate plain text representation of the Html text. Vice versa, setting this property overrides the HtmlLongText.
	LongText string `json:"longText,omitempty"`
	// This contains the Html representation of the Longtext. When the LongText is set, this is automatically overwritten and filled with the appropriate Html representation of the plaintext. Vice versa, setting this property overrides the LongText. GAEB 90 and GAEB 2000 exports do not support any image functionality. In GAEB XML, only images that use an embedded Base64 data uri are exported, regular url references are cleared before written out.
	HtmlLongText string          `json:"htmlLongText,omitempty"`
	AdditionType AdditionTypeDto `json:"additionType"`
	ElementType  string          `json:"elementType,omitempty"`
	// Quantity assignments are, in contrast to SubDescriptions, used to categorize parts of this Position. For example, it could be categorized by cost group - e.g. a Position describing concrete walls could follow the German DIN 276 Cost Groups Standard and specify that of the total 1.000m² wall, 500m² are classified as exterior walls and 500m² are classified as interior walls. They would then have different cost groups associated, e.g. for accounting purposes.
	QuantityAssignments []QuantityAssignmentDto `json:"quantityAssignments,omitempty"`
	CommerceProperties  CommercePropertiesDto   `json:"commerceProperties,omitempty"`
	// If this position is an Alternative, then this property should point to the id of the position in this service specification that it can replace.
	AlternativeTo string `json:"alternativeTo,omitempty"`
	// If this is true, it indicates that the position is intended to be a lump sum, \"Pauschal\" in German. This means the position total price that is being invoiced should not depend on the actual quantity. In practice, partial invoices are still often used for partial services rendered. This property does not affect the price calculation for this position. Typically, the Quantity should be set to 1.0 when this flag is used.
	IsLumpSum bool `json:"isLumpSum"`
	// This identifier can be used to point to the Id of a position in the same ServiceSpecification that acts as a base position. It matches \"Bezugsposition\" in GAEB. This can be used for positions that repeat partially or are linked together
	RepetitionTo string `json:"repetitionTo,omitempty"`
	// These are Catalogues that are used within this Position. Catalogues are used to describe catalogues, or collections, that can be used to describe elements with commonly known properties. For example, QuantityAssignments use these to categorize themselves. They are propagate to all child elements, e.g. other containers and QuantityAssignments. In the context of a ServiceSpecification, all elements share the same instance of the collection.
	ProjectCatalogues []CatalogueDto `json:"projectCatalogues,omitempty"`
	// Referenced catalogues for this Position.
	CatalogueReferences     []CatalogueReferenceDto    `json:"catalogueReferences,omitempty"`
	Type                    string                     `json:"type,omitempty"`
	StandardizedDescription StandardizedDescriptionDto `json:"standardizedDescription,omitempty"`
	// This list contains references to positions that complement this one, additionally also specifying a quantity for which the addition is intended. This does not replace the ComplementedBy property and there are no automatic checks being done between these two properties, so it's up to the user code to ensure deletions (and additions, if desired) are performed for both properties. When copying withing keeping Ids, this list will not be part of the copy process, since it would only contain quantities without actual position references. Containers, however, will rebuild the list with updated position references when copying positions that contain entries here.
	ComplementedByQuantities []ComplementedByQuantityDto `json:"complementedByQuantities,omitempty"`
	// This identifier can be used to point to the Id of an ExecutionDescription in the same ServiceSpecification. ExecutionDescriptions act as a way to centrally describe how positions should be executed in practice. Often, the position itself still has text of its own to highlight deviations from that or add more details.
	ExecutionDescriptionReference string `json:"executionDescriptionReference,omitempty"`
}
