/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// ComissionStatusDto Indicates if this service specification item is commissioned (and therefore should be executed), postponed for later or undefined.
type ComissionStatusDto string

// List of ComissionStatusDto
const (
	COMISSIONSTATUSDTO_UNDEFINED    ComissionStatusDto = "Undefined"
	COMISSIONSTATUSDTO_COMMISSIONED ComissionStatusDto = "Commissioned"
	COMISSIONSTATUSDTO_POSTPONED    ComissionStatusDto = "Postponed"
	COMISSIONSTATUSDTO_REMOVED      ComissionStatusDto = "Removed"
)
