/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// CalculationDto This class holds means to calculate mathematical expressions from given strings.
type CalculationDto struct {
	// Descriptive text for this calculation.
	Description string `json:"description,omitempty"`
	// This Calculation's mathematical expression. Please note that thousands separators are not supported. Both comma and point will be treated as decimal separators.
	Formula string `json:"formula,omitempty"`
	// The calculated result from the formula, 0 if invalid.
	Result float64 `json:"result"`
	// Whether the Formula is a valid expression.
	Valid bool `json:"valid"`
	// Will be -1 if the Formula is correct, else it will show the position in the formula where an error was encountered. This is a zero based index.
	ErrorPositionInLine int32 `json:"errorPositionInLine"`
}
