/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// DestinationOenormType Represents valid Oenorm target types
type DestinationOenormType string

// List of DestinationOenormType
const (
	DESTINATIONOENORMTYPE_LV2015 DestinationOenormType = "Lv2015"
	DESTINATIONOENORMTYPE_LB2015 DestinationOenormType = "Lb2015"
)
