/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// PriceRoundingModeDto This enum configures rounding modes for price calculations in projects
type PriceRoundingModeDto string

// List of PriceRoundingModeDto
const (
	PRICEROUNDINGMODEDTO_NORMAL  PriceRoundingModeDto = "Normal"
	PRICEROUNDINGMODEDTO_FLOOR   PriceRoundingModeDto = "Floor"
	PRICEROUNDINGMODEDTO_CEILING PriceRoundingModeDto = "Ceiling"
)
