/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// ExchangePhaseDto Indicates a ServiceSpecification's exchange phase, based on the GAEB exchange phases.
type ExchangePhaseDto string

// List of ExchangePhaseDto
const (
	EXCHANGEPHASEDTO_UNDEFINED     ExchangePhaseDto = "Undefined"
	EXCHANGEPHASEDTO_BASE          ExchangePhaseDto = "Base"
	EXCHANGEPHASEDTO_COST_ESTIMATE ExchangePhaseDto = "CostEstimate"
	EXCHANGEPHASEDTO_OFFER_REQUEST ExchangePhaseDto = "OfferRequest"
	EXCHANGEPHASEDTO_OFFER         ExchangePhaseDto = "Offer"
	EXCHANGEPHASEDTO_SIDE_OFFER    ExchangePhaseDto = "SideOffer"
	EXCHANGEPHASEDTO_GRANT         ExchangePhaseDto = "Grant"
)
