/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// CatalogueTypeDto This enumeration describes the type of a catalogue. Catalogues, or collections, hold information to categorize and describe items. For example, the German DIN 276 cost group standards describe different types of costs for building projects. When referencing the DIN 276 catalogue and providing an item key or identifier, it is possible to reference data in this catalogue.
type CatalogueTypeDto string

// List of CatalogueTypeDto
const (
	CATALOGUETYPEDTO_UNKNOWN       CatalogueTypeDto = "Unknown"
	CATALOGUETYPEDTO_LOCATION      CatalogueTypeDto = "Location"
	CATALOGUETYPEDTO_DIN276        CatalogueTypeDto = "DIN276"
	CATALOGUETYPEDTO_COST_UNIT     CatalogueTypeDto = "CostUnit"
	CATALOGUETYPEDTO_WORK_CATEGORY CatalogueTypeDto = "WorkCategory"
)
