/*
AVACloud API 1.41.4

AVACloud API specification

API version: 1.41.4
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package avaclient

import (
	"encoding/json"
)

// checks if the TokenRefreshPost type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TokenRefreshPost{}

// TokenRefreshPost struct for TokenRefreshPost
type TokenRefreshPost struct {
	RefreshToken string `json:"refreshToken"`
}

// NewTokenRefreshPost instantiates a new TokenRefreshPost object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTokenRefreshPost(refreshToken string) *TokenRefreshPost {
	this := TokenRefreshPost{}
	this.RefreshToken = refreshToken
	return &this
}

// NewTokenRefreshPostWithDefaults instantiates a new TokenRefreshPost object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTokenRefreshPostWithDefaults() *TokenRefreshPost {
	this := TokenRefreshPost{}
	return &this
}

// GetRefreshToken returns the RefreshToken field value
func (o *TokenRefreshPost) GetRefreshToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RefreshToken
}

// GetRefreshTokenOk returns a tuple with the RefreshToken field value
// and a boolean to check if the value has been set.
func (o *TokenRefreshPost) GetRefreshTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RefreshToken, true
}

// SetRefreshToken sets field value
func (o *TokenRefreshPost) SetRefreshToken(v string) {
	o.RefreshToken = v
}

func (o TokenRefreshPost) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TokenRefreshPost) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["refreshToken"] = o.RefreshToken
	return toSerialize, nil
}

type NullableTokenRefreshPost struct {
	value *TokenRefreshPost
	isSet bool
}

func (v NullableTokenRefreshPost) Get() *TokenRefreshPost {
	return v.value
}

func (v *NullableTokenRefreshPost) Set(val *TokenRefreshPost) {
	v.value = val
	v.isSet = true
}

func (v NullableTokenRefreshPost) IsSet() bool {
	return v.isSet
}

func (v *NullableTokenRefreshPost) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTokenRefreshPost(val *TokenRefreshPost) *NullableTokenRefreshPost {
	return &NullableTokenRefreshPost{value: val, isSet: true}
}

func (v NullableTokenRefreshPost) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTokenRefreshPost) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
