/*
 * AVACloud API 1.16.0
 *
 * AVACloud API specification
 *
 * API version: 1.16.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package avaclient

// ItemNumberSchemaDto The schema for ItemNumber's in a Project.
type ItemNumberSchemaDto struct {
	// The count of tiers in the ItemNumberSchema
	TotalLength int32 `json:"totalLength"`
	// The collection of tiers for this ItemNumberSchema.
	Tiers []ItemNumberSchemaTierDto `json:"tiers,omitempty"`
}
